CREATE TABLE users
(
    id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    name VARCHAR (60) UNIQUE NOT NULL,
    username VARCHAR (60) UNIQUE NOT NULL,
    password_hash VARCHAR (20) NOT NULL,
    email VARCHAR (150) NOT NULL,
    is_admin BOOLEAN NOT NULL
);

CREATE TABLE posts
(
    id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    contents TEXT NOT NULL,
    user_id BIGINT REFERENCES users(id) NOT NULL
);